language: cpp

dist: xenial
addons:
  apt:
    packages:
      - libace-dev
      - libace-ssl-dev
      - libace-inet-dev
      - libace-inet-ssl-dev
      - libtinyxml-dev
      - zlib1g-dev
      - libssl-dev
      - libopus-dev
      - libspeex-dev
      - libspeexdsp-dev
      - libvpx-dev
      - libogg-dev
      - portaudio19-dev
      - libasound2-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavfilter-dev
      - libavformat-dev
      - libavresample-dev
      - libavutil-dev
      - libswresample-dev
      - libswscale-dev
      - openjdk-8-jdk
      - cmake
      - qt5-default
      - qtmultimedia5-dev
      - libqt5x11extras5-dev
      - libqt5webkit5-dev
#      - qtwebengine5-dev (ubuntu 18)
      - junit4
      - python3-minimal

# Library/TeamTalkLib/toolchain has many submodules
git:
  submodules: false

env:
  global:
# TeamTalkJNI JUnit environment variables
    - INPUTDEVICEID=1978
    - OUTPUTDEVICEID=1978
    - OPUSTOOLS=0

script:
# Source env (LD_LIBRARY_PATH, PYTHONPATH, etc)
  - cd $TRAVIS_BUILD_DIR
  - source env.sh
# Build libraries, server binaries and examples
  - mkdir build
  - cd build
  - cmake -DBUILD_TEAMTALK_CORE=ON -DBUILD_TEAMTALK_STATIC=OFF -DBUILD_TEAMTALK_ACE=OFF -DSPEEXDSP_STATIC=OFF -DFFMPEG_STATIC=OFF -DAVF=OFF -DMSDMO=OFF -DDSHOW=OFF -DVIDCAP=OFF -DMEDIAFOUNDATION=OFF -DOPUS_STATIC=OFF -DLIBVPX_STATIC=OFF -DSPEEX_STATIC=OFF -DOGG_STATIC=OFF -DOPUSTOOLS=OFF -DLAMEMP3=OFF -DMSVS_UNITTEST=OFF -DACE_STATIC=OFF -DTINYXML_STATIC=OFF -DPORTAUDIO_STATIC=OFF -DZLIB_STATIC=OFF ..
  - make -j4
# Build Qt clients
  - cd $TRAVIS_BUILD_DIR
  - cd Client/qtTeamTalk
  - qmake CONFIG+=nowebengine teamtalk5.pro
  - make -j4
  - make clean
  - qmake CONFIG+=nowebengine teamtalk5pro.pro
  - make -j4
# Run JUnit suite TeamTalkServerTestSuite.java
  - cd $TRAVIS_BUILD_DIR
  - cd Library/TeamTalkJNI
  - make runjunitsrv
# Start TeamTalk Standard Server non-encrypted mode for JUnit suite TeamTalkStdTestSuite.java
  - cd $TRAVIS_BUILD_DIR
  - cp Library/TeamTalkLib/test/tt5srv.xml_template Server/tt5srv.xml
  - Server/tt5srv -d -c Server/tt5srv.xml
  - cd $TRAVIS_BUILD_DIR
  - cd Library/TeamTalkJNI
  - make runjunit
  - killall tt5srv
# Start TeamTalk Pro Server non-encrypted mode for JUnit suite TeamTalkProTestSuite.java
  - cd $TRAVIS_BUILD_DIR
  - cp -f Library/TeamTalkLib/test/tt5srv.xml_template Server/tt5srv.xml
  - Server/tt5prosrv -d -c Server/tt5srv.xml
  - cd $TRAVIS_BUILD_DIR
  - cd Library/TeamTalkJNI
  - export ENCRYPTED=0
  - make runjunitpro
  - killall tt5prosrv
# Start TeamTalk Pro Server in encrypted mode for JUnit suite TeamTalkProTestSuite.java
  - cd $TRAVIS_BUILD_DIR
  - cp Library/TeamTalkLib/test/tt5prosrv.xml_template Server/tt5prosrv.xml
  - cp Library/TeamTalkLib/test/ttservercert.pem Server/
  - cp Library/TeamTalkLib/test/ttserverkey.pem Server/
  - Server/tt5prosrv -d -wd Server/
  - cd Library/TeamTalkJNI
  - export ENCRYPTED=1
  - make runjunitpro
# Start Python client example and ensure it connects
  - cd $TRAVIS_BUILD_DIR
  - make -C Client/ttserverlogpy
  - killall tt5prosrv
# Run JUnit suite TeamTalkServerTestSuite.java in encrypted mode
  - cd $TRAVIS_BUILD_DIR
  - cd Library/TeamTalkJNI
  - make runjunitsrv
